### ISSUE TITLE
object2Form?

### ISSUE THREAD

**Issue by dandv** [serbanghita/form-to-object#14]
Salut,

This looks like one of [the nicest no-jQuery](https://github.com/marioizquierdo/jquery.serializeJSON#alternatives) solution for serializing a form to JSON.

Any plans to add the reverse operation, setting the default values of form elements from data in an object?

**Comment by serbanghita** [comment]
Salut,

This is a good idea! :bulb:  I haven't had this need until recently!
I can provide a different file called `objectToForm.js` to do this, that exposes `objectToForm` function. I'm not sure about the input though:

```javascript
objectToForm({
 username: 'serbanghita',
 settings: {
  race: 'human',
  age: 100,
  input: 'mouse'
 },
 country: 'Romania',
 interests: ['coding', 'startups']
});
```

Do you have multi dimensional objects that need to be mapped to forms?

**Comment by dandv** [comment]
Thanks, `objectToForm` would be nice. The fields in my form are flat; no hierarchy.

**Comment by serbanghita** [comment]
I've launched https://github.com/serbanghita/form-to-object/releases/tag/3.0.0-rc.0

After giving this an additional thought, this doesn't really make sense in today's world where you build an SPA with React, Vue, etc.
Maybe I'm missing something ...
