### ISSUE TITLE
Can I convert some input into an array?

### ISSUE THREAD

**Issue by littlee** [serbanghita/form-to-object#17]
``` html
<input type="hidden" name="a[arr][0]" value="12" />
<input type="hidden" name="a[arr][1]" value="34" />
```

will be convert to this

``` js
{
    "a": {
        "arr": {
            "0": "12",
            "1": "34"
        }
    }
}
```

how to make it like this?

``` js
{
    "a": {
        "arr": ["12", "34"]
    }
}
```

**Comment by serbanghita** [comment]
I'm looking into this. This is tricky because it has to be an `Array` and both an `Object` in the same time. Some have stuff like `a[arr][0], a[arr][1], a[arr]['stuff']`. Thanks for noticing this

**Comment by serbanghita** [comment]
I have two distinct situations:

```html
<input type="hidden" name="a[arr][0]" value="12" />
<input type="hidden" name="a[arr][1]" value="34" />
```

which should result in 

```json
{
    "a": {
        "arr": ["12", "34"]
    }
}
```

and

```html
<input type="hidden" name="a[arr][name]" value="Serban" />
<input type="hidden" name="a[arr][age]" value="99" />
```

which should result in 

```json
{
    "a": {
        "arr": {
          "name": "Serban",
          "age": "99"
        }
    }
}
```

If you have any suggestions how to do this, please reply. I'm thinking of subclassing the `Array` prototype.

**Comment by serbanghita** [comment]
Also there is the situation when the key doesn't start from `0`

```html
<input type="hidden" name="a[arr][55]" value="12" />
<input type="hidden" name="a[arr][88]" value="34" />
```

**Comment by littlee** [comment]
I think you can follow the `body-parser` way:

```html
<input type="text" name="caruosel[0][link]" value="c link 0">
<input type="text" name="caruosel[0][src]" value="c src 0">
<input type="text" name="caruosel[11][link]" value="c link 1">
<input type="text" name="caruosel[11][src]" value="c src 1">
```

wiil be

```js
{
    "caruosel": [
        {
            "link": "c link 0",
            "src": "c src 0"
        },
        {
            "link": "c link 1",
            "src": "c src 1"
        }
    ]
}
```

and

```html
<input type="text" name="caruosel[0][link]" value="c link 0">
<input type="text" name="caruosel[0][src]" value="c src 0">
<input type="text" name="caruosel[a11][link]" value="c link 1">
<input type="text" name="caruosel[a11][src]" value="c src 1">
```

will be:

```js
{
    "caruosel": {
        "10": {
            "link": "c link 0",
            "src": "c src 0"
        },
        "a11": {
            "link": "c link 1",
            "src": "c src 1"
        }
    }
}
```

**Comment by serbanghita** [comment]
@littlee Interesting, not sure about the numeric key example, it resets your key value when you get back the `object` to a server request. Maybe this should be a limitation ...
I'm looking at https://github.com/expressjs/body-parser right now.

In the meanwhile I decided to start writing unit tests for `formToObject` so I can make these kind of refactoring decisions much easier for the future.

**Comment by littlee** [comment]
I might find a good way for this issue
check this out
https://lodash.com/docs#values

it can convert object to array

**Comment by Merwer** [comment]
I might've recommended a different approach.

Instead of using `<input name="obj[foo]">` as the syntax, using `<input name="obj.foo">` allows for a distinction between arrays and object properties.

**Comment by serbanghita** [comment]
@Merwer parsing and interpreting field names like `obj.foo.bar` is a good idea, it's a different patch though.

**Comment by littlee** [comment]
@serbanghita Hey, it's almost 2 years since my create this issue, I'm still expecting a array parsing feature.
Here's my proposal:
if the parsed value is "strictly ordered" and starts from "0", it should be pared to an array.
```
<input type="hidden" name="a[0]" value="12" />
<input type="hidden" name="a[1]" value="34" />
```
will get
```
{
  a: [12, 34]
}
```
---
```
<input type="hidden" name="a[2]" value="12" />
<input type="hidden" name="a[5]" value="34" />
```
will get
```
{
  a: {
   "2" : 12,
   "5": 34 
  }
}
```

Believe yourself, you can do it. 💪 💪 💪

**Comment by serbanghita** [comment]
@littlee thanks for making the context more clear! Stay tuned 💥

**Comment by jonatasdaniel** [comment]
Waiting for this feature too :)

**Comment by serbanghita** [comment]
Done in https://github.com/serbanghita/form-to-object/releases/tag/3.0.0-rc.0
