### ISSUE TITLE
wrong format single checkbox

### ISSUE THREAD

**Issue by crashbtz** [serbanghita/form-to-object#4]
Hi,
Thanks for your job, that's help me a lot with my symfony project but I have an issue with the checkbox element.
You return an array even if it's a single checkbox instead of return the value.
Maybe I'm wrong but I guess it's an array if there are many checkbox but just a value if it's a single one.

**Comment by PeteAUK** [comment]
Just started to use this for form submission using AJAX and noticed that single checkboxes handle as an array which led me to this issue and discussion.

Justification for not submitting single checkboxes as an array is simply that any Javascript routine should mimic the browsers native HTML POST method.  In the case of single checkboxes, the native method doesn't convert it to an array.  If you have multiple checkboxes with a single name then the native method simply passes the last set value - no "arraification" at all.

The reason for this is that if you cannot assume the client is using a JS enabled browser in 100% of cases - I'm looking at accessibility browsers or some security driven industries.  The non-JS fallback in those handful of cases will be the browsers own native method.  By changing it to an array the server side code needs to handle both singular and array passed values.

**Comment by serbanghita** [comment]
Fixed in https://github.com/serbanghita/form-to-object/releases/tag/3.0.0-rc.0

**Comment by serbanghita** [comment]
Only took about ~10 yrs, but hey, it's fixed now 🥇 🙇 🤣
